module.exports = async ({page, base, ok}) => {
  await page.evaluate(() => localStorage.clear()); await page.reload({waitUntil:'networkidle'});
  ok('starts with hotel + slots folded', (await page.locator('.day.folded').count()) === 1 && (await page.locator('.slot.folded').count()) === 10 && (await page.locator('.opt:visible').count()) === 0);
  await page.locator('#unfoldAll').click();
  await page.locator('#who button[data-p="D"]').click();
  const n = await page.locator('.opt').count(); ok('options rendered', n > 80, `(${n})`);
  const missing = await page.evaluate(() => AVAIL.filter(a => !ALL[a.id]).map(a => a.id)); ok('no missing option ids', missing.length === 0, missing.join(','));
  const slots = await page.locator('.slot').count(); ok('10 slots + hotel', slots === 11, `(${slots})`);
  const first = page.locator('.opt').first();
  await first.locator('.vote button.y').click(); ok('vote marks option', await first.evaluate(c => c.classList.contains('v-y')));
  await first.locator('.more').click(); ok('details open', await first.evaluate(c => c.classList.contains('open')));
  await page.locator('#who button[data-p="A"]').click(); ok('switch person', (await page.locator('#barWho').textContent()) === 'Amanda');
  for (const k of ['hotel|h-drury','fri-full|cm-fri','fri-eve|fri-foodtrucks','sat-am|sat-market','sat-pm|aia','sat-eve|wind-pool','sun-am|pumpkin-russell','sun-pm|home-uranus']) await page.locator(`.opt[data-key="${k}"] .vote button.y`).click();
  const y = await page.evaluate(() => Object.values(JSON.parse(localStorage.getItem('carmel-slots-v1')).votes.A).filter(v=>v==='y').length); ok('yes votes recorded', y === 8, `(${y})`);
  await page.locator('[data-fold="sat-pm"]').click(); ok('slot folds with picks', (await page.locator('#s-sat-pm.folded').count()) === 1 && (await page.locator('#s-sat-pm .sl').textContent()).includes('Arts in Autumn'));
  await page.locator('[data-fold="fri"]').click(); ok('day folds', (await page.locator('#d-fri.folded .fsum').count()) === 1);
  await page.locator('#unfoldAll').click(); ok('expand all', (await page.locator('.folded').count()) === 0);
  await page.locator('#foldDone').click(); ok('fold voted slots', (await page.locator('.slot.folded').count()) >= 6);
  await page.locator('#unfoldAll').click();
  const code = await page.evaluate(() => encode('A')); ok('encode', /^A\.[ymn.]+\./.test(code));
  await page.evaluate(() => localStorage.clear()); await page.goto('about:blank'); await page.goto(base + '/#s=' + code, {waitUntil:'networkidle'}); await page.waitForTimeout(300);
  const st = await page.evaluate(() => JSON.parse(localStorage.getItem('carmel-slots-v1'))); ok('import via hash', Object.values(st.votes.A).filter(v=>v==='y').length === 8);
  ok('hash cleared', (await page.evaluate(() => location.hash)) === '');
  ok('plan shows waiting rows', (await page.locator('.prow .st.wait').count()) >= 8);
  await page.locator('[data-map="sat-pm"]').click();
  await page.waitForFunction(() => document.querySelectorAll('#map path.leaflet-interactive').length > 0, null, {timeout: 15000});
  const pins = await page.locator('#map path.leaflet-interactive').count(); ok('slot map pins', pins >= 8, `(${pins})`);
  ok('slot filter preselected', await page.locator('#mapf button.on').getAttribute('data-f') === 'sat-pm');
  await page.locator('#mapf button[data-f="hotel"]').click(); ok('hotel pins', (await page.locator('#map path.leaflet-interactive').count()) === 7);
  await page.locator('#mapClose').click(); ok('modal closes', await page.locator('#mapModal').evaluate(m => m.hidden));
  await page.setViewportSize({width:390,height:844}); await page.waitForTimeout(200);
  ok('no horizontal scroll on mobile', await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1));
  await page.evaluate(() => { try{localStorage.clear()}catch(e){} });
};
