// ---- Friday evening in Carmel ----
{id:'fri-foodtrucks',block:'fri-pm',rec:true,title:'Carmel Food Truck Nights: season finale',when:'Fri Oct 16 · ~5–9pm (listings vary 5–8)',where:'Ginther Green, 930 N Range Line Rd, Carmel',
 why:'Your arrival night is the last Food Truck Friday of the season. Free entry, pay per truck, casual, outdoors, lots of choice for a picky 5-year-old. Gets cold and dark after 7, so go at 5:30.',
 tags:['free:Free entry','Food','Outdoor','kid:Easy'],
 body:'<p>Not at Midtown; Ginther Green is a private lot on Range Line about a mile north. The weekly truck lineup posts on the Facebook page Sunday night. Organizers added shade this year. Parking: unstated, lot plus street.</p><div class="tip">Pairs with Holliday Park or Westermeier Commons on the way in, then an early bedtime. Keeps Saturday night free for Conner Prairie if you want both.</div>',
 links:[{t:'Visit Hamilton County listing',u:'https://www.visithamiltoncounty.com/event/carmel-food-truck-fridays/77721/'},{t:'Current in Carmel: 2026 season',u:'https://www.youarecurrent.com/2026/04/23/carmel-food-truck-nights-gears-up-for-second-season/'},{t:'Facebook (weekly lineup)',u:'https://www.facebook.com/carmelfoodtrucklot/'}],map:'Ginther Green 930 N Range Line Rd Carmel'},
{id:'fri-pumpkintown',block:'fri-pm',title:'Sullivan Express train to PumpkinTown (Fishers)',when:'Fri, Sat, Sun · times by reservation',where:'Allisonville Home & Garden, 11405 Allisonville Rd, Fishers',
 why:'A little train through an “Enchanted Forest” to a pumpkin village with games and fall food. $75 per train car (up to 4 adults + 2 kids), so about $25 a head. Times sell out; call 317-255-9230.',
 tags:['cost:$75 per car','kid:Built for this age','Outdoor'],
 body:'<p>Dates listed include Oct 16, 17 and 18. Departure times and age rules are not published; the store says train times go quickly. 15 minutes from Carmel, near Conner Prairie.</p>',
 links:[{t:'Visit Hamilton County listing',u:'https://www.visithamiltoncounty.com/event/sullivan-express-to-pumpkintown/78785/'},{t:'Sullivan Hardware events',u:'https://sullivanhardware.com/pages/events'}],map:'Allisonville Home and Garden by Sullivan Fishers'},

// ---- Saturday morning Carmel ----
{id:'sat-market',block:'sat-am',rec:true,title:'Carmel Winter Farmers Market opening day + steel drums',when:'Sat Oct 17 · 9am–noon',where:'The Six Eleven, 611 3rd Ave SW, Carmel',
 why:'Opening day of the indoor winter market: ~60 vendors, breakfast items, a café seating area, and the Island Breeze steel-drum band. Free, five minutes from Midtown, and it leaves the whole morning loose.',
 tags:['free:Free','in:Indoor','kid:Music + snacks'],
 body:'<p>The summer market at Carter Green ended in September. The site still has a stale “510 3rd Ave SW” line; 611 is the current address. Crowded indoors on opening day, so go at 9.</p><div class="tip">Hotel breakfast first, market at 9:30 for a second snack, then a park (Westermeier Commons or West Park) until lunch. Leaves the afternoon fully open.</div>',
 links:[{t:'Winter market page',u:'https://www.carmelfarmersmarket.com/wm-home'}],map:'611 3rd Ave SW Carmel IN'},
{id:'sat-train',block:'sat-am',title:'Nickel Plate Express “Fall Foliage Express” (Noblesville)',when:'Sat Oct 17 or Sun Oct 18 · times not posted',where:'825 Forest Park Dr, Noblesville · 20 min',
 why:'A 65-minute real-train ride with cider and a fall treat. Adult $28, child 3–12 $26, so about $82 for the three of you. Not offered Friday. Works as the Saturday “big thing” (morning or afternoon, depending on departure times) or a Sunday add before the drive.',
 tags:['cost:~$82 family','kid:All ages','Train'],
 body:'<p>Departure times are not on the calendar page; book to see them. “Pumpkin Express” no longer runs. Caboose seats $20, Diamond Class $35.</p>',
 links:[{t:'Fall Foliage Express',u:'https://nickelplateexpress.com/fall-foliage-express/'},{t:'All train rides',u:'https://nickelplateexpress.com/train-rides/'}],map:'Nickel Plate Express Noblesville'},

// ---- Carmel Saturday afternoon ----
{id:'aia',block:'carmel',rec:true,title:'Arts in Autumn at Midtown Plaza',when:'Sat Oct 17 · 2–5pm',where:'Midtown Plaza, 365 Monon Blvd, Carmel',
 why:'Free craft stations, face painting, balloon artists, seasonal photo spots, vendors, Touch-a-Truck with Carmel fire and police vehicles, and an outdoor showing of Encanto on the Midtown screen.',
 tags:['free:Free','kid:Crafts, trucks, Encanto','Outdoor'],
 body:'<div class="grid2"><div><b>Movie</b>Encanto, per the city news release. Showtime not published (2025 was 3pm). Check @midtowncarmel or call 317-571-2400.</div><div><b>Parking</b>Free garages: Midtown West / Railyard garage at 350 Monon Blvd (370 spaces), or the garage on Elm St next to Java House, across from the plaza (public restrooms inside). Street parking also free.</div></div>
 <div class="k">Midtown Plaza for families (Indy’s Child)</div><ul><li>Big climbing playground with a rock-climbing hill on turf</li><li>Two splash pads (almost certainly off in mid-October)</li><li>Ping pong, shuffleboard, cornhole, bocce; shaded tables</li><li>“Sail,” a 29-ft sculpture you can stand inside</li><li>Sun King Spirits food hall (pizza, tacos), Fork + Ale House, Java House, Penn &amp; Beech pour-your-own candles</li></ul>
 <div class="warn">Clay Terrace Boo ’n Brew runs 2–6pm the same afternoon, 6 miles away. Pick one, or do Boo ’n Brew 2–4 and come to Midtown for the movie if the showtime is late.</div><div class="tip">Bring a blanket and layers for the movie; sunset is about 7pm and it drops into the 40s.</div>',
 links:[{t:'City event page',u:'https://www.carmel.in.gov/our-city/experience/events-and-festivals/the-arts-in-autumn'},{t:'City calendar entry',u:'https://www.carmel.in.gov/Calendar.aspx?EID=1123&month=10&year=2026&day=17&calType=0'},{t:'City news release (Encanto, Touch-a-Truck)',u:'https://www.carmel.in.gov/m/newsflash?cat=1'},{t:'Midtown Plaza events',u:'https://midtownplazacarmel.com/upcoming-events/'},{t:'Indy’s Child: Midtown for families',u:'https://indyschild.com/midtown-plaza-carmel-for-families/'},{t:'Indy With Kids: Midtown',u:'https://indywithkids.com/midtown-carmel/'}],map:'Midtown Plaza Carmel'},
{id:'boonbrew',block:'carmel',rec:true,title:'Clay Terrace Boo ’n Brew Fall Festival',when:'Sat Oct 17 · 2–6pm',where:'14390 Clay Terrace Blvd, Carmel',
 why:'Honestly more kid content than Arts in Autumn: trick-or-treating at stores with a pumpkin sign, free hayrides 2:30–5:30, Silly Safaris animal show at 2:30 and 4, bounce house, corn maze, pumpkin decorating, face painters, kids’ band at 4. Free. Bring a tote and a costume.',
 tags:['free:Free','kid:Trick-or-treat + hayride','Outdoor','Costumes'],
 body:'<div class="k">Schedule</div><ul><li>2:00 JAMBOX on the main stage</li><li>2:30 &amp; 4:00 Silly Safaris animal show</li><li>2:30–5:30 hayrides</li><li>3:00 Pet Zone costume contest</li><li>4:00 Toy Factory (kids’ band)</li><li>All day: live pumpkin carving, balloon twisters, face painting, bounce house, selfie station, corn maze, family-friendly beer garden (Upland, Bier, Field)</li></ul><p>Rules: no outside food or alcohol, no lawn chairs in the beer garden. Parking map PDF on the event page. No rain plan listed. Phone 317-818-0725.</p><div class="warn">Same afternoon as Arts in Autumn. A split (Boo ’n Brew 2–4:15, then Midtown for the movie) works only if Encanto starts after 4:30.</div>',
 links:[{t:'Clay Terrace official event page',u:'https://www.clayterrace.com/events/boo-n-brew-2026'},{t:'Visit Hamilton County listing',u:'https://www.visithamiltoncounty.com/event/clay-terrace-boo-n-brew/78599/'}],map:'Clay Terrace Carmel'},
{id:'minis',block:'carmel',title:'Suzie Moffett’s Caged Rooms at the Museum of Miniature Houses',when:'Fri/Sat 11am–4pm · Sun 1–4pm',where:'111 E Main St, Carmel (Arts & Design District)',
 why:'Not a haunted thing: miniature rooms built inside antique birdcages, in a dollhouse museum. $10 adults, $5 kids 3–9. Look-don’t-touch, so 45 minutes tops. A good cold-or-rain filler, steps from Bub’s ice cream.',
 tags:['cost:$25 family','in:Indoor','Rain plan'],
 body:'<p>Exhibit runs Oct 7, 2026 to Oct 17, 2027. Closed Mon–Tue. Phone 317-575-9466.</p>',
 links:[{t:'Visit Hamilton County listing',u:'https://www.visithamiltoncounty.com/event/suzie-moffetts-caged-rooms/78274/'},{t:'Museum of Miniature Houses',u:'https://museumofminiatures.org/'}],map:'Museum of Miniature Houses Carmel'},
{id:'history',block:'carmel',title:'Carmel Clay History Museum play floor',when:'Wed–Sat 10–6 · Sun 12–5',where:'Monon Depot, one block south of Main St',
 why:'Free admission through 2026; the third-floor kids’ area with themed playhouses is $1 per child. Twenty-minute stop on the Monon between Midtown and Main Street.',
 tags:['free:Free ($1 play floor)','in:Indoor','kid:Playhouses'],
 body:'',links:[{t:'Indy With Kids listing',u:'https://indywithkids.com/locations/carmel-clay-history-museum/'}],map:'Carmel Clay History Museum'},

// ---- Parks ----
{id:'park-westermeier',block:'parks',rec:true,title:'Westermeier Commons (Central Park)',when:'Dawn–dusk',where:'920 Central Park Dr W, Carmel',
 why:'25,000+ sq ft playground with climbing walls, next to the Monon Community Center. Closest big playground to Midtown, so the default “we have 45 minutes” stop.',
 tags:['free:Free','kid:Huge playground','Outdoor'],
 body:'',links:[{t:'Indy With Kids: Carmel playgrounds',u:'https://indywithkids.com/playgrounds-carmel-parks/'}],map:'Westermeier Commons Carmel'},
{id:'park-west',block:'parks',title:'West Park: nature playground, zipline, pond',when:'Dawn–dusk',where:'2700 W 116th St, Carmel',
 why:'Best all-round Carmel park: two-level playground, nature-adventure area, zipline, sledding hill, pond loop. 10 minutes west of Midtown.',
 tags:['free:Free','kid:Zipline','Outdoor'],
 body:'<p>Splash pad is seasonal (assume off).</p>',links:[{t:'Indy With Kids: Carmel playgrounds',u:'https://indywithkids.com/playgrounds-carmel-parks/'}],map:'West Park Carmel IN'},
{id:'park-flatfork',block:'parks',title:'Flat Fork Creek Park treehouses (Fishers)',when:'Dawn–dusk',where:'16141 E 101st St, Fishers · 15–20 min',
 why:'Three real treehouses (one fully accessible), a pond and a sledding hill. Not a swings-and-slides park; the treehouses are the whole point for a 5-year-old.',
 tags:['free:Free','kid:Treehouses','Outdoor'],
 body:'',links:[{t:'Indy With Kids listing',u:'https://indywithkids.com/locations/flat-fork-creek-park/'}],map:'Flat Fork Creek Park Fishers'},
{id:'park-coxhall',block:'parks',title:'Coxhall Gardens Children’s Garden',when:'Dawn–dusk',where:'11677 Towne Rd, Carmel',
 why:'Miniature village storefronts, a rainbow path and kite fields, with fall color. More wander than climb.',
 tags:['free:Free','Outdoor','Photos'],
 body:'',links:[{t:'Indy With Kids: Carmel playgrounds',u:'https://indywithkids.com/playgrounds-carmel-parks/'}],map:'Coxhall Gardens Carmel'},
{id:'park-founders',block:'parks',title:'Founders Park giant sandbox',when:'Dawn–dusk',where:'11675 Hazel Dell Pkwy, Carmel',
 why:'A giant sandbox and nature swings. Bring a change of clothes.',
 tags:['free:Free','Outdoor'],
 body:'',links:[{t:'Indy With Kids: Carmel playgrounds',u:'https://indywithkids.com/playgrounds-carmel-parks/'}],map:'Founders Park Carmel'},
{id:'monon-center',block:'parks',title:'Rain or cold plan: Monon Community Center pool + indoor playground',when:'Sat 12–7 (pool), 1–6 (playground) · Sun 9am–7pm / 9–6',where:'1235 Central Park Dr E, Carmel',
 why:'Indoor activity pool with slides (48″ for slides) plus the Monon Station indoor playground, all on a day pass: $15 for Valerie, $18 per adult, bought in person with a waiver. The outdoor waterpark is closed for the season.',
 tags:['cost:~$51 family','in:Indoor','kid:Pool + playground','Pool'],
 body:'<p>Children 5 and under must have a parent within arm’s reach in the water. If the hotel has a pool, this is redundant; if not, it is the swim.</p>',
 links:[{t:'Monon Community Center',u:'https://www.carmelclayparks.com/monon-community-center/'},{t:'Monon Station indoor playground',u:'https://www.carmelclayparks.com/amenities/monon-station-indoor-playground/'}],map:'Monon Community Center Carmel'},

// ---- Eat ----
{id:'eat-bubs',block:'eat',rec:true,title:'Bub’s Burgers & Ice Cream',when:'Lunch/dinner',where:'210 W Main St, Carmel (Arts & Design District)',
 why:'The Carmel kid classic: “Little Bub’s” meal with a busy bag, ice cream counter inside. Walkable to the miniatures museum and Main Street.',
 tags:['cost:$','Food','kid:Ice cream'],body:'',links:[{t:'Indy With Kids: Carmel family restaurants',u:'https://indywithkids.com/'}],map:'Bub\'s Burgers Carmel'},
{id:'eat-sunking',block:'eat',title:'Sun King Spirits food hall at Midtown',when:'Lunch/dinner',where:'Midtown Plaza, Carmel',
 why:'Pizza (Pi) and tacos (La Margarita) with a patio and rooftop, right at the Arts in Autumn site. Kid-friendly outside the bar area.',
 tags:['cost:$$','Food'],body:'<p>Alternatives on the plaza: Fork + Ale House (350 Veterans Way, patio by the green) and Social Cantina (350 Monon Blvd, $5 kids’ meals).</p>',links:[{t:'Indy’s Child: Midtown for families',u:'https://indyschild.com/midtown-plaza-carmel-for-families/'}],map:'Sun King Spirits Carmel'},
{id:'eat-rosies',block:'eat',title:'Rosie’s Place (breakfast all day)',when:'Breakfast/lunch',where:'1111 W Main St, Carmel',
 why:'If the hotel breakfast disappoints or you want a Sunday send-off: pancakes and French toast all day.',
 tags:['cost:$$','Food'],body:'<p>Other Main Street options with real kids’ menus: Muldoon’s (111 W Main, indoor family area), Woody’s Library (40 E Main), Papa Fattoush (15 E Main, kids’ gyro).</p>',links:[],map:'Rosie\'s Place Carmel'},
{id:'eat-sweets',block:'eat',title:'Donuts and ice cream',when:'Any',where:'Carmel',
 why:'Pana Donuts & Boba (2284 E 116th St, ~40 varieties, from 5am), Graeter’s (864 S Rangeline Rd), Handel’s, Rita’s Italian Ice downtown. Jack’s Donuts on Carmel Dr was announced but not confirmed open.',
 tags:['cost:$','Food','kid:Obviously'],body:'',links:[],map:'Pana Donuts Carmel'},
{id:'eat-tpc',block:'eat',title:'Sunday brunch at Traders Point Creamery (Zionsville)',when:'Sat–Sun 10am–2:30pm',where:'Zionsville · ~20 min',
 why:'Organic dairy farm with The Loft restaurant; brunch and a walk past the cows. A gentler Sunday morning if you skip the museum. Farm-tour and hayride details for 2026 not confirmed.',
 tags:['cost:$$$','Food','Outdoor'],body:'',links:[{t:'Traders Point Creamery',u:'https://www.traderspointcreamery.com/'}],map:'Traders Point Creamery'},
