// ---- Friday evening in Carmel ----
{id:'fri-foodtrucks',block:'fri-pm',rec:true,title:'Carmel Food Truck Nights: season finale',when:'Fri Oct 16 · ~5–9pm (listings vary 5–8)',where:'Ginther Green, 930 N Range Line Rd, Carmel',
 why:'Your arrival night is the last Food Truck Friday of the season. Free entry, pay per truck, casual, outdoors, lots of choice for a picky 5-year-old. Gets cold and dark after 7, so go at 5:30.',
 tags:['free:Free entry','Food','Outdoor','kid:Easy'],
 body:'<p>Not at Midtown; Ginther Green is a private lot on Range Line about a mile north. The weekly truck lineup posts on the Facebook page Sunday night. Organizers added shade this year. Parking: unstated, lot plus street.</p><div class="tip">Pairs with Holliday Park or Westermeier Commons on the way in, then an early bedtime. Keeps Saturday night free for Conner Prairie if you want both.</div>',
 links:[{t:'Visit Hamilton County listing',u:'https://www.visithamiltoncounty.com/event/carmel-food-truck-fridays/77721/'},{t:'Current in Carmel: 2026 season',u:'https://www.youarecurrent.com/2026/04/23/carmel-food-truck-nights-gears-up-for-second-season/'},{t:'Facebook (weekly lineup)',u:'https://www.facebook.com/carmelfoodtrucklot/'}],map:'Ginther Green 930 N Range Line Rd Carmel'},
{id:'fri-pumpkintown',block:'fri-pm',title:'Sullivan Express train to PumpkinTown (Fishers)',when:'Fri, Sat, Sun · times by reservation',where:'Allisonville Home & Garden, 11405 Allisonville Rd, Fishers',
 why:'A little train through an “Enchanted Forest” to a pumpkin village with games and fall food. $75 per train car (up to 4 adults + 2 kids), so about $25 a head. Times sell out; call 317-255-9230.',
 tags:['cost:$75 per car','kid:Built for this age','Outdoor'],
 body:'<p>Dates listed include Oct 16, 17 and 18. Departure times and age rules are not published; the store says train times go quickly. 15 minutes from Carmel, near Conner Prairie.</p>',
 links:[{t:'Visit Hamilton County listing',u:'https://www.visithamiltoncounty.com/event/sullivan-express-to-pumpkintown/78785/'},{t:'Sullivan Hardware events',u:'https://sullivanhardware.com/pages/events'}],map:'Allisonville Home and Garden by Sullivan Fishers'},

// ---- Saturday morning Carmel ----
{id:'sat-market',block:'sat-am',rec:true,title:'Carmel Winter Farmers Market opening day + steel drums',when:'Sat Oct 17 · 9am–noon',where:'The Six Eleven, 611 3rd Ave SW, Carmel',
 why:'Opening day of the indoor winter market: ~60 vendors, breakfast items, a café seating area, and the Island Breeze steel-drum band. Free, five minutes from Midtown, and it leaves the whole morning loose.',
 tags:['free:Free','in:Indoor','kid:Music + snacks'],
 body:'<p>The summer market at Carter Green ended in September. The site still has a stale “510 3rd Ave SW” line; 611 is the current address. Crowded indoors on opening day, so go at 9.</p><div class="tip">Hotel breakfast first, market at 9:30 for a second snack, then a park (Westermeier Commons or West Park) until lunch. Leaves the afternoon fully open.</div>',
 links:[{t:'Winter market page',u:'https://www.carmelfarmersmarket.com/wm-home'}],map:'611 3rd Ave SW Carmel IN'},
{id:'sat-train',also:['sun-am'],block:'sat-am',title:'Nickel Plate Express “Fall Foliage Express” (Noblesville)',when:'Sat Oct 17 (times unposted) · Sun Oct 18 departs 1:00pm',where:'825 Forest Park Dr, Noblesville · 20 min',
 why:'A 65-minute real-train ride with cider and a fall treat. Adult $28, child 3–12 $26, about $82 for three. Not offered Friday. Sunday’s run leaves at 1:00 and ends about 2:05, which pushes your departure to 2:30 and home to ~6:30. Saturday is the cleaner fit if times work.',
 tags:['cost:~$82 family','kid:All ages','Train'],
 body:'<p>Sunday 1pm time is from Indy’s Child; the official page shows the date but no times, and the booking page didn’t load. Saturday departures unknown; book to see them. “Pumpkin Express” no longer runs. Caboose $20, Diamond $35. Hobbs Station, 825 Forest Park Dr.</p>',
 links:[{t:'Fall Foliage Express',u:'https://nickelplateexpress.com/fall-foliage-express/'},{t:'All train rides',u:'https://nickelplateexpress.com/train-rides/'},{t:'Indy’s Child listing (1pm Sunday)',u:'https://indyschild.com/events/location/nickel-plate-express/'}],map:'Nickel Plate Express Noblesville'},

// ---- Carmel Saturday afternoon ----
{id:'aia',block:'carmel',rec:true,title:'Arts in Autumn at Midtown Plaza',when:'Sat Oct 17 · 2–5pm',where:'Midtown Plaza, 365 Monon Blvd, Carmel',
 why:'Free craft stations, face painting, balloon artists, seasonal photo spots, vendors, Touch-a-Truck with Carmel fire and police vehicles, and an outdoor showing of Encanto on the Midtown screen.',
 tags:['free:Free','kid:Crafts, trucks, Encanto','Outdoor'],
 body:'<div class="grid2"><div><b>Movie</b>Encanto, per the city news release. Showtime not published (2025 was 3pm). Check @midtowncarmel or call 317-571-2400.</div><div><b>Parking</b>Free garages: Midtown West / Railyard garage at 350 Monon Blvd (370 spaces), or the garage on Elm St next to Java House, across from the plaza (public restrooms inside). Street parking also free.</div></div>
 <div class="k">Midtown Plaza for families (Indy’s Child)</div><ul><li>Big climbing playground with a rock-climbing hill on turf</li><li>Two splash pads (almost certainly off in mid-October)</li><li>Ping pong, shuffleboard, cornhole, bocce; shaded tables</li><li>“Sail,” a 29-ft sculpture you can stand inside</li><li>Sun King Spirits food hall (pizza, tacos), Fork + Ale House, Java House, Penn &amp; Beech pour-your-own candles</li></ul>
 <div class="warn">Clay Terrace Boo ’n Brew runs 2–6pm the same afternoon, 6 miles away. Pick one, or do Boo ’n Brew 2–4 and come to Midtown for the movie if the showtime is late.</div><div class="tip">Bring a blanket and layers for the movie; sunset is about 7pm and it drops into the 40s.</div>',
 links:[{t:'City event page',u:'https://www.carmel.in.gov/our-city/experience/events-and-festivals/the-arts-in-autumn'},{t:'City calendar entry',u:'https://www.carmel.in.gov/Calendar.aspx?EID=1123&month=10&year=2026&day=17&calType=0'},{t:'City news release (Encanto, Touch-a-Truck)',u:'https://www.carmel.in.gov/m/newsflash?cat=1'},{t:'Midtown Plaza events',u:'https://midtownplazacarmel.com/upcoming-events/'},{t:'Indy’s Child: Midtown for families',u:'https://indyschild.com/midtown-plaza-carmel-for-families/'},{t:'Indy With Kids: Midtown',u:'https://indywithkids.com/midtown-carmel/'}],map:'Midtown Plaza Carmel'},
{id:'boonbrew',block:'carmel',rec:true,title:'Clay Terrace Boo ’n Brew Fall Festival',when:'Sat Oct 17 · 2–6pm',where:'14390 Clay Terrace Blvd, Carmel',
 why:'Honestly more kid content than Arts in Autumn: trick-or-treating at stores with a pumpkin sign, free hayrides 2:30–5:30, Silly Safaris animal show at 2:30 and 4, bounce house, corn maze, pumpkin decorating, face painters, kids’ band at 4. Free. Bring a tote and a costume.',
 tags:['free:Free','kid:Trick-or-treat + hayride','Outdoor','Costumes'],
 body:'<div class="k">Schedule</div><ul><li>2:00 JAMBOX on the main stage</li><li>2:30 &amp; 4:00 Silly Safaris animal show</li><li>2:30–5:30 hayrides</li><li>3:00 Pet Zone costume contest</li><li>4:00 Toy Factory (kids’ band)</li><li>All day: live pumpkin carving, balloon twisters, face painting, bounce house, selfie station, corn maze, family-friendly beer garden (Upland, Bier, Field)</li></ul><p>Rules: no outside food or alcohol, no lawn chairs in the beer garden. Parking map PDF on the event page. No rain plan listed. Phone 317-818-0725.</p><div class="warn">Same afternoon as Arts in Autumn. A split (Boo ’n Brew 2–4:15, then Midtown for the movie) works only if Encanto starts after 4:30.</div>',
 links:[{t:'Clay Terrace official event page',u:'https://www.clayterrace.com/events/boo-n-brew-2026'},{t:'Visit Hamilton County listing',u:'https://www.visithamiltoncounty.com/event/clay-terrace-boo-n-brew/78599/'}],map:'Clay Terrace Carmel'},
{id:'minis',also:['sun-am'],block:'carmel',title:'Suzie Moffett’s Caged Rooms at the Museum of Miniature Houses',when:'Fri/Sat 11am–4pm · Sun 1–4pm',where:'111 E Main St, Carmel (Arts & Design District)',
 why:'Not a haunted thing: miniature rooms built inside antique birdcages, in a dollhouse museum. $10 adults, $5 kids 3–9. Look-don’t-touch, so 45 minutes tops. A good cold-or-rain filler, steps from Bub’s ice cream.',
 tags:['cost:$25 family','in:Indoor','Rain plan'],
 body:'<p>Exhibit runs Oct 7, 2026 to Oct 17, 2027. Closed Mon–Tue. Phone 317-575-9466.</p>',
 links:[{t:'Visit Hamilton County listing',u:'https://www.visithamiltoncounty.com/event/suzie-moffetts-caged-rooms/78274/'},{t:'Museum of Miniature Houses',u:'https://museumofminiatures.org/'}],map:'Museum of Miniature Houses Carmel'},
{id:'history',also:['sun-am'],block:'carmel',title:'Carmel Clay History Museum play floor',when:'Wed–Sat 10–6 · Sun 12–5',where:'Monon Depot, one block south of Main St',
 why:'Free admission through 2026; the third-floor kids’ area with themed playhouses is $1 per child. Twenty-minute stop on the Monon between Midtown and Main Street.',
 tags:['free:Free ($1 play floor)','in:Indoor','kid:Playhouses'],
 body:'',links:[{t:'Indy With Kids listing',u:'https://indywithkids.com/locations/carmel-clay-history-museum/'}],map:'Carmel Clay History Museum'},

// ---- Sunday morning ----
{id:'sun-cp',block:'sun-am',also:['sat-am'],title:'Conner Prairie by day (Fishers)',when:'Sun (and Sat) · 10am–4pm',where:'13400 Allisonville Rd, Fishers · 15 min',
 why:'The daytime version of the Headless Horseman grounds: Treetop Outpost four-story treehouse, animals, 1836 Prairietown. $26 adult / $20 youth at the gate, $2 less online, about $70 for the three of you. A solid 10–1:30 that ends at the right time.',
 tags:['cost:~$70 family','kid:Treehouse + animals','Outdoor','Sunday-proof'],
 body:'<p>Open Tue–Sun through Oct 30. The hiking Trails are closed from flood damage. Balloon ride is a separate ticket ($19/$11) and weather-dependent. Half-price after 3pm (in person) is no use with a 2pm departure.</p><div class="warn">If you also do the Headless Horseman festival, this is a second admission; the festival grounds close at 4 and reopen at 5 on a separate ticket.</div>',
 links:[{t:'Hours & admission',u:'https://www.connerprairie.org/plan/hours-and-admission/'}],map:'Conner Prairie'},
{id:'park-coolcreek',block:'parks',also:['sun-am'],title:'Cool Creek Park: big shaded playground + nature play',when:'Dawn–dusk · nature center Sun 1–5',where:'2000 E 151st St, Carmel/Westfield · 10 min',
 why:'Free, large shaded playground with toddler and big-kid sections plus a nature playground. The Nature Center (turtles, snakes, a tortoise) doesn’t open until 1 on Sunday, so it is a playground stop in the morning.',
 tags:['free:Free','kid:Playground','Outdoor'],
 body:'<p>Phone 317-774-2500 for any Oct 18 programming (the Oct 17 “Plants with a Haunted History” hike is Saturday only).</p>',
 links:[{t:'Indy With Kids listing',u:'https://indywithkids.com/locations/cool-creek-park-nature-center/'}],map:'Cool Creek Park Nature Center'},

// ---- Parks ----
{id:'park-westermeier',also:['sun-am'],block:'parks',rec:true,title:'Westermeier Commons (Central Park)',when:'Dawn–dusk',where:'920 Central Park Dr W, Carmel',
 why:'25,000+ sq ft playground with climbing walls, next to the Monon Community Center. Closest big playground to Midtown, so the default “we have 45 minutes” stop.',
 tags:['free:Free','kid:Huge playground','Outdoor'],
 body:'',links:[{t:'Indy With Kids: Carmel playgrounds',u:'https://indywithkids.com/playgrounds-carmel-parks/'}],map:'Westermeier Commons Carmel'},
{id:'park-west',also:['sun-am'],block:'parks',title:'West Park: nature playground, zipline, pond',when:'Dawn–dusk',where:'2700 W 116th St, Carmel',
 why:'Best all-round Carmel park: two-level playground, nature-adventure area, zipline, sledding hill, pond loop. 10 minutes west of Midtown.',
 tags:['free:Free','kid:Zipline','Outdoor'],
 body:'<p>Splash pad is seasonal (assume off).</p>',links:[{t:'Indy With Kids: Carmel playgrounds',u:'https://indywithkids.com/playgrounds-carmel-parks/'}],map:'West Park Carmel IN'},
{id:'park-flatfork',also:['sun-am'],block:'parks',title:'Flat Fork Creek Park treehouses (Fishers)',when:'Dawn–dusk',where:'16141 E 101st St, Fishers · 15–20 min',
 why:'Three real treehouses (one fully accessible), a pond and a sledding hill. Not a swings-and-slides park; the treehouses are the whole point for a 5-year-old.',
 tags:['free:Free','kid:Treehouses','Outdoor'],
 body:'',links:[{t:'Indy With Kids listing',u:'https://indywithkids.com/locations/flat-fork-creek-park/'}],map:'Flat Fork Creek Park Fishers'},
{id:'park-coxhall',also:['sun-am'],block:'parks',title:'Coxhall Gardens Children’s Garden',when:'Dawn–dusk',where:'11677 Towne Rd, Carmel',
 why:'Miniature village storefronts, a rainbow path and kite fields, with fall color. More wander than climb.',
 tags:['free:Free','Outdoor','Photos'],
 body:'',links:[{t:'Indy With Kids: Carmel playgrounds',u:'https://indywithkids.com/playgrounds-carmel-parks/'}],map:'Coxhall Gardens Carmel'},
{id:'park-founders',block:'parks',title:'Founders Park giant sandbox',when:'Dawn–dusk',where:'11675 Hazel Dell Pkwy, Carmel',
 why:'A giant sandbox and nature swings. Bring a change of clothes.',
 tags:['free:Free','Outdoor'],
 body:'',links:[{t:'Indy With Kids: Carmel playgrounds',u:'https://indywithkids.com/playgrounds-carmel-parks/'}],map:'Founders Park Carmel'},
{id:'monon-center',also:['sun-am'],block:'parks',title:'Rain or cold plan: Monon Community Center pool + indoor playground',when:'Sat 12–7 (pool), 1–6 (playground) · Sun 9am–7pm / 9–6',where:'1235 Central Park Dr E, Carmel',
 why:'Indoor activity pool with slides (48″ for slides) plus the Monon Station indoor playground, all on a day pass: $15 for Valerie, $18 per adult, bought in person with a waiver. The outdoor waterpark is closed for the season.',
 tags:['cost:~$51 family','in:Indoor','kid:Pool + playground','Pool'],
 body:'<p>Children 5 and under must have a parent within arm’s reach in the water. If the hotel has a pool, this is redundant.</p><div class="warn">One reading of the hours page says the indoor activity pool and slides are closed along with the outdoor waterpark this season. Call 317-848-7275 before counting on a swim.</div>',
 links:[{t:'Monon Community Center',u:'https://www.carmelclayparks.com/monon-community-center/'},{t:'Monon Station indoor playground',u:'https://www.carmelclayparks.com/amenities/monon-station-indoor-playground/'}],map:'Monon Community Center Carmel'},

// ---- Eat ----
{id:'eat-bubs',block:'eat',rec:true,title:'Bub’s Burgers & Ice Cream',when:'Lunch/dinner',where:'210 W Main St, Carmel (Arts & Design District)',
 why:'The Carmel kid classic: “Little Bub’s” meal with a busy bag, ice cream counter inside. Walkable to the miniatures museum and Main Street.',
 tags:['cost:$','Food','kid:Ice cream'],body:'',links:[{t:'Indy With Kids: Carmel family restaurants',u:'https://indywithkids.com/'}],map:'Bub\'s Burgers Carmel'},
{id:'eat-sunking',block:'eat',title:'Sun King Spirits food hall at Midtown',when:'Lunch/dinner',where:'Midtown Plaza, Carmel',
 why:'Pizza (Pi) and tacos (La Margarita) with a patio and rooftop, right at the Arts in Autumn site. Kid-friendly outside the bar area.',
 tags:['cost:$$','Food'],body:'<p>Alternatives on the plaza: Fork + Ale House (350 Veterans Way, patio by the green) and Social Cantina (350 Monon Blvd, $5 kids’ meals).</p>',links:[{t:'Indy’s Child: Midtown for families',u:'https://indyschild.com/midtown-plaza-carmel-for-families/'}],map:'Sun King Spirits Carmel'},
{id:'eat-rosies',also:['sun-am'],block:'eat',title:'Breakfast out instead of the hotel',when:'Sunday from 8am',where:'Carmel',
 why:'If the hotel breakfast disappoints or you want a Sunday send-off. Café Patachou at Clay Terrace is the verified one: Sunday 8am–3pm, made-to-order. Rosie’s Place (1111 W Main, ~8–2) and Garden Table at Midtown (Sun 9–3 brunch) are the local favorites; both unverified for hours.',
 tags:['cost:$$','Food'],body:'<p>First Watch (Village Park Plaza) is the chain fallback. Egg &amp; I Carmel closed years ago. Dinner on Main Street with real kids’ menus: Muldoon’s (111 W Main, indoor family area), Woody’s Library (40 E Main), Papa Fattoush (15 E Main, kids’ gyro).</p>',links:[{t:'Café Patachou, Clay Terrace',u:'https://www.clayterrace.com/dine/cafe-patachou'}],map:'Cafe Patachou Clay Terrace Carmel'},
{id:'eat-sweets',block:'eat',title:'Donuts and ice cream',when:'Any',where:'Carmel',
 why:'Pana Donuts & Boba (2284 E 116th St, ~40 varieties, from 5am), Graeter’s (864 S Rangeline Rd), Handel’s, Rita’s Italian Ice downtown. Jack’s Donuts on Carmel Dr was announced but not confirmed open.',
 tags:['cost:$','Food','kid:Obviously'],body:'',links:[],map:'Pana Donuts Carmel'},
{id:'eat-tpc',also:['sun-am'],block:'eat',title:'Traders Point Creamery: brunch + $5 farm walk (Zionsville)',when:'Sun · brunch 10–2:30, farm walk 10–3',where:'Zionsville · ~20 min',
 why:'Organic dairy farm 20 minutes west. Brunch at The Loft (reserve on OpenTable; $12–25 plates, no kids’ menu listed) then the self-guided 1.5-mile pasture walk, $5 per person, no reservation. Breakfast and activity in one stop, out by 1.',
 tags:['cost:$$$ brunch, $5 walk','Food','Outdoor','Sunday-proof'],body:'<p>No 2026 hayride or pumpkin event found; call 317-733-1700. Cows may not be close to the trail.</p>',links:[{t:'Brunch',u:'https://www.traderspointcreamery.com/brunch/'},{t:'Farm walk & tours',u:'https://www.traderspointcreamery.com/events/tours/'}],map:'Traders Point Creamery'},
